# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

#language: objective-c
#xcode_project: .xcodeproj # path to your xcodeproj folder
#xcode_scheme: MyNewProjectTests

osx_image: xcode8.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild clean build test -project HomeSurveillance.xcodeproj -scheme HomeSurveillance -configuration Debug | xcpretty && exit ${PIPESTATUS[0]}
#- pod lib lint
